####
# GitLab CI
####

# Image
image: openjdk:8-jdk-alpine

# Variables
variables:
  # Submodule Support (Hugo)
  GIT_SUBMODULE_STRATEGY: recursive

# Stages
stages:
  - build
  - test
  - docs
  - publishStage
  - publishStable

# Build
Assemble:
  stage: build
  script:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - ./gradlew assemble

# Test
Run Tests:
  stage: test
  script:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - ./gradlew test

###
# Test Documentation
###
test:
  image: registry.gitlab.com/pages/hugo:latest
  stage: docs
  script:
  - cd docs
  - hugo
  except:
  - master

###
# Build & Publish on GitLab Pages
###
pages:
  image: registry.gitlab.com/pages/hugo:latest
  stage: docs
  script:
  - cd docs
  - hugo --baseUrl https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}/
  - cp -R public ../
  artifacts:
    paths:
    - public
  only:
  - master
  - feature/work-in-progress

###
# Pre-Release
###
Publish Prerelease:
  stage: publishStage
  script:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - ./gradlew artifactoryPublish -Dsnapshot=true
  only:
  - /^v[0-9]+\.[0-9]+\.[0-9]+\-alpha\.[0-9]+$/
  - /^v[0-9]+\.[0-9]+\.[0-9]+\-beta\.[0-9]+$/
  - /^v[0-9]+\.[0-9]+\.[0-9]+\-rc\.[0-9]+$/

###
# Stable Release
###
Publish Release:
  stage: publishStable
  script:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - ./gradlew bintrayUpload
  only:
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/
